authors:
  - Jeremy Shoeneman
classifiers:
  - "Template :: Site :: Credentials"
  - "Template :: Site :: Training"
description: |
  This template represents a full website for company surveys
  to be used for credential gathering.
homepage: https://github.com/securestate/king-phisher
pages:
  - /404.html
  - /email.html
  - /examples.html
  - /index.html
  - /login.html
  - /phished.html
  - /plans.html
title: Survey Hound
version: 1.0
